name: Notify Update By Bot
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      older_commit:
        description: '古い方のコミットハッシュ（またはブランチ名）'
        required: true
        default: HEAD~1
      newer_commit:
        description: '新しい方のコミットハッシュ（またはブランチ名）'
        required: true
        default: HEAD

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ vars.SERVER_URL }}
    env:
      SERVER_URL: ${{ vars.SERVER_URL }}
      PAGES_URL: ${{ vars.PAGES_URL }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      OLDER: ${{ inputs.older_commit || github.event.before }}
      NEWER: ${{ inputs.newer_commit || github.event.after }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: 20.x
      - name: Setup
        run: |
          npm install -g corepack@latest
          corepack enable
          pnpm i --frozen-lockfile
      - name: Run scripts/notify-update-by-bot.mjs
        run: |
          node scripts/notify-update-by-bot.mjs
